name: Publish page

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: auto-deploy
        run: |
          cd ../../
          bash deploy.sh
